In [1]:
import numpy as np
import math 

In [2]:
n_prisoners = 6


def assign(n_prisoners):
    
    prisoners_array = np.arange(1,n_prisoners+1)
    cards_array = np.arange(1,n_prisoners+1)
    #np.random.shuffle(prisoners_array)
    np.random.shuffle(cards_array)
    
    
    shuffle = np.ndarray([2,n_prisoners],dtype=int)
    
    
    #print("prisoners: ", prisoners_array)
    #print("cards: ", cards_array)
    #print(shuffle)
    for i in range(0,n_prisoners):
        #print(i)
        shuffle[0,i] = prisoners_array[i]
        shuffle[1,i] = cards_array[i]
    return shuffle

In [3]:
g_shuffle = assign(n_prisoners)
g_shuffle

array([[1, 2, 3, 4, 5, 6],
       [4, 1, 3, 6, 5, 2]])

In [4]:
assign(n_prisoners)[0].shape[0]

6

In [5]:
def check(shuffle_array):
    #success = 0 
    #fail = 0
    #n_exp = 0
    checks = 0
    l = math.ceil(n_prisoners/2)
    check_array = []
    #print("l = ", l)
    #for j in g_shuffle[0]:
       
    for i in range(0,assign(n_prisoners)[0].shape[0]):
        for checks in range(0,l):
        #while checks < l:

            #print("i before = ", i)
            #print("checks=", checks)

            g1 =  g_shuffle[1][i]
            #print("g[1] =", g1)
            g, = np.where(g_shuffle[0] == g_shuffle[1][i])
            check_array.append(g1)
            i = g[0]

                #checks+=1
                
              
        
            
        
        #print("check array = ", check_array)
        
    print("g_shuffle = ", g_shuffle)
        
    return check_array

In [6]:
ca = check(g_shuffle)

g_shuffle =  [[1 2 3 4 5 6]
 [4 1 3 6 5 2]]


In [7]:
np.asarray(ca)

array([4, 6, 2, 1, 4, 6, 3, 3, 3, 6, 2, 1, 5, 5, 5, 2, 1, 4])

In [8]:
split_ca = np.array_split(ca,n_prisoners)
split_ca

[array([4, 6, 2]),
 array([1, 4, 6]),
 array([3, 3, 3]),
 array([6, 2, 1]),
 array([5, 5, 5]),
 array([2, 1, 4])]

In [9]:
success=0
for i in range(0,n_prisoners):
    print("g = ", g_shuffle[0][i])
    print(split_ca[i])
    for j in split_ca[i]:
        if g_shuffle[0][i] == j:
            success += 1
            break
if success == n_prisoners:
    print

g =  1
[4 6 2]
g =  2
[1 4 6]
g =  3
[3 3 3]
g =  4
[6 2 1]
g =  5
[5 5 5]
g =  6
[2 1 4]
2


In [11]:
def condition(g_shuffle):
    for j in g_shuffle[0]:
        ch = check(g_shuffle)
        i=j
        print(ch)
        print(g_shuffle[0][j])